### ISSUE TITLE
Android userLocation bearing arrow is not working properly

### ISSUE THREAD

**Issue by pstevens74** [react-native-community/react-native-maps#1069]
Hi,

I've successfully implemented the awesome airbnb mapview into my app and it's working brilliantly on IOS.  However, on Android the little arrow on the blue dot that is supposed to show you which way you are pointing your phone is wildly inaccurate.  It does move every now and then, but not in any direction that makes sense and seems to jump around.  The actual location is perfect as I walk around outside it's exactly right, but I just want to know if it's possible to get that arrow working as it should so my users can know which way to walk.     

I used google maps actual app in the same place on the same device and their bearing cone worked fine.

I have the following permissions in my manifest:

SYSTEM_ALERT_WINDOW
ACCESS_LOCATION
ACCESS_LOCATION_EXTRA_COMMANDS
ACCESS_COARSE_LOCATION
INTERNET
ACCESS_FINE_LOCATION

Here is how i've embedded the map:
          <MapView
            ref={(ref) => { this.mapRef = ref }}
            style={{flex:1}}
            mapType={mapType}
            region={{latitude: latitude, longitude: longitude, latitudeDelta: zoom, longitudeDelta: zoom}}
            showsUserLocation={true}
            followsUserLocation={this.props.followsLocation}
            rotateEnabled={true}
            scrollEnabled={true}
            zoomEnabled={true}
            showsPointsOfInterest={false}
            showsMyLocationButton={false}
            showsScale={false}
            showsCompass={false}
            pitchEnabled={false}
            toolbarEnabled={false}
          >

I'm running on react 0.39 as couldn't get mapview to work at all with 0.40.  

Any ideas if there is something else I need to do?  Or does the google arrow just not really work very well?

Thanks in advance!

**Comment by chrise86** [comment]
@pstevens74 how did you manage to get the direction/heading arrow to show on iOS? I have the same setup as yours but don't see the arrow, only the blue dot.

**Comment by namgk** [comment]
@chrise86 Probably you're not using google as the provider?

**Comment by christopherdro** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!

**Comment by CrisHemswerthThor** [comment]
I am also getting through it and it is really frustrating. In my case it is shown in IOS but not on android.
Is there any update on this issue?

**Comment by creat-or** [comment]
I also have this issue and created a repository with a minimal example and latest version to demonstrate the behavior. Would be really nice to get help with this issue!
When trying, just make sure to fill your `API_KEY` in `AndroidManifest.xml`. 

https://github.com/creat-or/MinimalMapsProject

Please reopen the issue :)
Thank you!

**Comment by toshe** [comment]
> It does move every now and then, but not in any direction that makes sense and seems to jump around

I can confirm the issue persists on Android. The blue arrow marker just "jumps" inaccurately from direction to direction. 
React Native: 0.61.5
React Native Maps: 0.27.0

**Comment by rborn** [comment]
@creat-or @toshe please open a new issue following the template and adding this example 😻

**Comment by creat-or** [comment]
@rborn Thank you!
@toshe @pstevens74 I made a new issue now in case you still need it https://github.com/react-native-community/react-native-maps/issues/3350
