### ISSUE TITLE
Android app crashes after adding the react-native-maps dependency

### ISSUE THREAD

**Issue by abhideepmallick** [react-native-community/react-native-maps#2880]
#2880  Bug

We have created a demo app with `react-native-maps` dependency. The project is a simple one and doesn't really render a map, but we have noticed that just after adding the dependancy the app started crashing in Android platform.

Here is a video reference of what is going on:

https://drive.google.com/open?id=11eZIEMjMEoOgQViVRS_JhTqHWu-Lnytk

## Environment info

React native info output:

```bash
 React Native Environment Info:
    System:
      OS: macOS 10.14.3
      CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
      Memory: 5.60 GB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.8.0 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.2.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 22, 23, 25, 26, 27, 28
        Build Tools: 23.0.1, 23.0.2, 25.0.0, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.1, 27.0.3, 28.0.2, 28.0.3, 29.0.0, 29.0.0
        System Images: android-19 | Google APIs Intel x86 Atom, android-21 | Intel x86 Atom, android-22 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-P | Google Play Intel x86 Atom, android-Q | Google Play Intel x86 Atom, android-Q | Google Play Intel x86 Atom_64
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.8 => 0.59.8 
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

Library version: ^0.24.2

## Steps To Reproduce

```
 Run it first time it’ll work.

`yarn add react-native-maps`
`react-native link`

Delete the app

Run it again

Broken
```

Describe what you expected to happen:

1. The app should not crash on launch

2. After giving the location permission the app should not crash

## Reproducible sample code

Here is the full project code:

[https://bitbucket.org/abhideep_appdukan/locationtest/src/master/](url)

**Comment by rborn** [comment]
you should not run `react-native link` by itself, you need to use it with the package you want to link `react-native link react-native-maps`

**Comment by abhideepmallick** [comment]
@rborn that didn't make any difference

**Comment by rborn** [comment]
@abhideepmallick I just downloaded your repo, ran `npm install` and `react-native run-android` and it started just fine (genymotion emulator android 9) 😐

**Comment by noahtallen** [comment]
You can look at `abd logcat` to see the native crash report as you open the app. That could help us figure out what the issue is. However, I was also recently getting a lot of crashes for devices on the latest version of Android and Crashlytics reported this crash:
```
Fatal Exception: java.lang.NoClassDefFoundError
Failed resolution of: Lorg/apache/http/ProtocolVersion;
```
This is an [issue](https://stackoverflow.com/questions/50782806/android-google-maps-java-lang-noclassdeffounderror-failed-resolution-of-lorg-a) with the underlying maps library. Also[ see this official documentation from Google](https://developers.google.com/maps/documentation/android-sdk/config#specify_requirement_for_apache_http_legacy_library).

The solution: put this in the Manifest `<application>` tag:
```
<uses-library android:name="org.apache.http.legacy" android:required="false"/>
```

It might not be your issue, but it would be easy to try :)

**Comment by KirankumarDafda** [comment]
My android map was running fine before but now its stopped working just showing google logo and grey screen,

Package.json 

`
"react": "16.6.0-alpha.8af6728",
"react-native": "0.57.3",
"react-native-google-places-autocomplete": "^1.3.9",
"react-native-map-clustering": "^1.3.2",
"react-native-map-link": "^2.1.6",
"react-native-maps": "^0.23.0",
`
Also I have added Google API key in Android Manifest

 `<meta-data
        android:name="com.google.android.geo.API_KEY"
        android:value="key-goes-here"/>`

Please help.

**Comment by travis-cramer** [comment]
> The solution: put this in the Manifest `<application>` tag:
> 
> ```
> <uses-library android:name="org.apache.http.legacy" android:required="false"/>
> ```
> 
> It might not be your issue, but it would be easy to try :)

why does this work?

**Comment by noahtallen** [comment]
It's what Google says to do: https://developers.google.com/maps/documentation/android-sdk/config#specify_requirement_for_apache_http_legacy_library

I assume they updated how they consume a library and now for backwards compatibility (we are using an older version) we have to do that.

**Comment by joaopedrodcf** [comment]
> 
> The solution: put this in the Manifest `<application>` tag:
> 
> ```
> <uses-library android:name="org.apache.http.legacy" android:required="false"/>
> ```
> 
> It might not be your issue, but it would be easy to try :)

Worked perfectly 👍

**Comment by abhideepmallick** [comment]
This issue is fixed in the latest update of `react-native-maps`.

**Comment by emreSerbetcioglu** [comment]
Still having the issue in version 0.26.1

**Comment by Xerus2000** [comment]
Having this issue in a managed Expo App, maps version 0.26.1 and I can't modify my manifest...

**Comment by Tyldar** [comment]
I still have the issue with latest version. Had to use @noahtallen fix solution.

**Comment by GeorgeStratulat** [comment]
No idea what the error was, my application simply crashed when opening the map after updating to android sdk 28. @noahtallen  's answer saved my day

**Comment by ThevinMalaka** [comment]
> You can look at `abd logcat` to see the native crash report as you open the app. That could help us figure out what the issue is. However, I was also recently getting a lot of crashes for devices on the latest version of Android and Crashlytics reported this crash:
> 
> ```
> Fatal Exception: java.lang.NoClassDefFoundError
> Failed resolution of: Lorg/apache/http/ProtocolVersion;
> ```
> 
> This is an [issue](https://stackoverflow.com/questions/50782806/android-google-maps-java-lang-noclassdeffounderror-failed-resolution-of-lorg-a) with the underlying maps library. Also[ see this official documentation from Google](https://developers.google.com/maps/documentation/android-sdk/config#specify_requirement_for_apache_http_legacy_library).
> 
> The solution: put this in the Manifest `<application>` tag:
> 
> ```
> <uses-library android:name="org.apache.http.legacy" android:required="false"/>
> ```
> 
> It might not be your issue, but it would be easy to try :)

Thank you very much. You saved my day.

**Comment by DevilPatels** [comment]
i having issue like this

this is my logcat

java.lang.NoSuchMethodError: No static method getFusedLocationProviderClient(Landroid/content/Context;)Lcom/google/android/gms/location/FusedLocationProviderClient; in class Lcom/google/android/gms/location/LocationServices; or its super classes (declaration of 'com.google.android.gms.location.LocationServices' appears in /data/app/com.drapp-C1klWmBxCroOYpKkCWvoAw==/base.apk!classes2.dex)
        at com.airbnb.android.react.maps.FusedLocationSource.<init>(FusedLocationSource.java:22)
        at com.airbnb.android.react.maps.AirMapView.<init>(AirMapView.java:165)
        at com.airbnb.android.react.maps.AirMapManager.createViewInstance(AirMapManager.java:85)
        at com.airbnb.android.react.maps.AirMapManager.createViewInstance(AirMapManager.java:29)
        at com.facebook.react.uimanager.ViewManager.createViewInstance(ViewManager.java:139)
        at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:83)
        at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:270)
        at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:180)
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:987)
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:958)
        at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1083)
        at android.view.Choreographer.doCallbacks(Choreographer.java:908)
        at android.view.Choreographer.doFrame(Choreographer.java:831)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1070)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:228)
        at android.app.ActivityThread.main(ActivityThread.java:7782)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)

could anyone find solution for this ?

**Comment by jbrainz** [comment]
<uses-library android:name="org.apache.http.legacy" android:required="false"/>

i tried this still it is not working and i'm using latest version

**Comment by TheChanDI** [comment]
I having issue with latest version. I tried above solution but it is still crashing.

**Comment by jbrainz** [comment]
what i did was i just deleted the entire node_modules folder and the build folder in the app dir. and everything worked fine

**Comment by TheChanDI** [comment]
> I having issue with latest version. I tried above solution but it is still crashing.

Its working now. I just clean gradlew and it works now.

**Comment by karimdakroury** [comment]
Hi my apk keeps crashing when i am trying to navigate to the screen that uses react-native-maps. What should i do?
