### ISSUE TITLE
Got warning: "Require cycle" in MapView

### ISSUE THREAD

**Issue by l1fe** [react-native-community/react-native-maps#3352]
# Bug

Got require cycle warning with the 0.27.1 version of the library:

Warning: Require cycle: node_modules/react-native-maps/lib/components/MapView.js -> node_modules/react-native-maps/lib/components/Geojson.js -> node_modules/react-native-maps/lib/components/MapView.js

## Environment info

```
System:
    OS: macOS 10.15.2
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 44.52 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.10.0 - ~/.nvm/versions/node/v12.10.0/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.10.3 - ~/.nvm/versions/node/v12.10.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.1
      System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
  npmGlobalPackages:
    react-native-create-library: 3.1.2
```

Library version: 0.27.1

## Steps To Reproduce

1. Install react-native-maps
2. Mount `<MapView />`
...

Describe what you expected to happen:

1. No warnings

## Reproducible sample code

Plain <MapView />

**Comment by vishweshjoshi** [comment]
Hi All,

I am also getting same issue after adding mapview. Any solution or workaround for this?

**Comment by thuyngocha98** [comment]
same problem :(

**Comment by rborn** [comment]
This is warning, not harmful (yet) 
It needs some refactoring to remove it but is JS side only so any PR is gladly accepted 😀

**Comment by joaovitorzv** [comment]
same problem here

**Comment by itsam** [comment]
I second that!
Any solutions are highly appreciated. Thank you.

**Comment by siloob** [comment]
Hi, same problem here

**Comment by DalerAsrorov** [comment]
Just saw the same issue after adding the `MapView` component to the app.

**Comment by EdilsonAndrade** [comment]
Same issue here :-(

**Comment by robbroadwell** [comment]
I'm also seeing this warning, and the map isn't rendering.

**Comment by rdourado92** [comment]
Same problem here :P

**Comment by gride-nepal** [comment]
Same issue here 

 Require cycle: node_modules/react-native-maps/lib/components/MapView.js -> node_modules/react-native-maps/lib/components/MapPolygon.js -> node_modules/react-native-maps/lib/components/MapView.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.

**Comment by nurmohammed840** [comment]
How to rid of those warn?

**Comment by nethusan** [comment]
Got the same problem, any updates?

**Comment by nick-bull** [comment]
This has caused my map to stop rendering - it is more than just a warning!

**Comment by alihasana** [comment]
Got the same problem, any updates please?

**Comment by JamesKemp296** [comment]
Also having the same issue in my app.

**Comment by rborn** [comment]
Any PR is welcome 😉

**Comment by diegomart2000** [comment]
hey @rborn I do have a branch locally with a simple refactor to fix this. It is pretty straight forward. I can't push it tho.

**Comment by myty** [comment]
@diegomart2000 We must be thinking along the same lines.  I just pushed up a PR.  Want to take a look and compare? #3424

**Comment by diegomart2000** [comment]
@myty 100% the same exact thing.

**Comment by rborn** [comment]
@myty @diegomart2000 😻

**Comment by xDemon200** [comment]
fix solucion by @myty with forked 
yarn add https://github.com/xDemon200/react-native-maps
npx react-native start 
npx react-native run-android

**Comment by itsam** [comment]
Works smoothly :) Thanks a lot all of you for your effort

**Comment by NSNJRGL** [comment]
Same problem here :)

**Comment by syngi** [comment]
Could a new version be released? 0.27.1 is the latest, but had the issue. Thanks!

**Comment by tinim123** [comment]
Same problem, help please

**Comment by myty** [comment]
> Same problem, help please

@syngi @tinim123 @NSNJRGL The easiest thing you can do until a new version is released is to do:
`yarn add git+https://github.com/react-native-community/react-native-maps.git` in your RN project.

**Comment by NSNJRGL** [comment]
yeap it's working

**Comment by itsam** [comment]
What I do to apply patches prior to release (in general) is to use https://www.npmjs.com/package/patch-package
I believe is most clean solution and works perfectly.

**Comment by pke** [comment]
> What I do to apply patches prior to release (in general) is to use [npmjs.com/package/patch-package](https://www.npmjs.com/package/patch-package)
> I believe is the most clean solution and works perfectly.

How would that work with that PR here now? Thanks.

**Comment by itsam** [comment]
@pke 
1) install patch-package.
2) create a folder in your project called "patches"
3) Inside "patches" folder get the patch from this gist (for convenience) https://gist.github.com/itsam/278a56a1f20a8b80e27c269d9fe83093
4) yarn install or npm install

Hope that helps

**Comment by pke** [comment]
@itsam This is genius! I will use it for all sorts of un-published patches now, thanks! 🚀

**Comment by tranvanquang** [comment]
I have same proplem :(( can u have solution for this warning?

**Comment by NSNJRGL** [comment]
> I have same proplem :(( can u have solution for this warning?

yarn add https://github.com/xDemon200/react-native-maps
npx react-native start
npx react-native run-android

It is working btw

**Comment by MarcoFromBerlin** [comment]
> @itsam This is genius! I will use it for all sorts of un-published patches now, thanks! 🚀
> 
> Important is to actually add the "postinstall" script with a `patch-package` call

Hi!
Can you explain what did you do?
Thanks!

**Comment by pke** [comment]
@MarcoFromBerlin I did what @itsam wrote step by step.

**Comment by MarcoFromBerlin** [comment]
ok. thanks.
actually now I don't get it anymore

**Comment by rodrigoincsoft** [comment]
Pessoal
Para mim ****RESOLVIDO da seguinte forma**:**
Entrar na pasta do componente em  ....\node_modules\react-native-maps\lib\components
Fazer as seguintes alterações

diff --git a/node_modules/react-native-maps/lib/components/Geojson.js b/node_modules/react-native-maps/lib/components/Geojson.js

Observe que ao lado da linha tem o sinal de menos(-) e mais(+) que indica o que deve ser substituído.

-import MapView from './MapView';         **<====Restirar esta linha**
+import Marker from './MapMarker';          **< ==== Acrescentar esta linha**
+import Polyline from './MapPolyline';            **< ==== Acrescentar esta linha**
+import Polygon from './MapPolygon';               **< ==== Acrescentar esta linha**
 
         if (overlay.type === 'point') {
           return (
-            <MapView.Marker        < ===  *****trocar isto
+            <Marker                        <==== por isto
               key={index}



         if (overlay.type === 'polygon') {
           return (
-            <MapView.Polygon
+            <Polygon
               key={index}


         if (overlay.type === 'polyline') {
           return (
-            <MapView.Polyline         < ===  *****trocar isto
+            <Polyline                        < ===== *****por apenas isto
               key={index}
               coordinates={overlay.coordinates}




///Neste outro componente
....modules/react-native-maps/lib/components/MapPolygon.js

   USES_DEFAULT_IMPLEMENTATION,
   SUPPORTED,
 } from './decorateMapComponent';
-import MapView from './MapView';
+import * as ProviderConstants from './ProviderConstants';
 
         onLayout={
-          this.context.provider === MapView.PROVIDER_GOOGLE       < ====trocar Isto
+          this.context.provider === ProviderConstants.PROVIDER_GOOGLE     <===Por isto
             ? this.updateNativeProps()
             : undefined
         }

**Comment by anlramirezs11** [comment]
> yarn add https://github.com/xDemon200/react-native-maps
> npx react-native start
> npx react-native run-android
> 

It doesn't work for me  :( :-1:

**Comment by ramafebri** [comment]
> @pke
> 
> 1. install patch-package.
> 2. create a folder in your project called "patches"
> 3. Inside "patches" folder get the patch from this gist (for convenience) https://gist.github.com/itsam/278a56a1f20a8b80e27c269d9fe83093
>    and name it as react-native-maps+0.27.1.patch
> 4. yarn install or npm install
> 
> Hope that helps

i have tried npx patch-package https://gist.github.com/itsam/278a56a1f20a8b80e27c269d9fe83093 and 
the result is "No such package https://gist.github.com/itsam/278a56a1f20a8b80e27c269d9fe83093"

How to get that patch correctly?

**Comment by FaycalBorsali** [comment]
> @pke
> 
> 1. install patch-package.
> 2. create a folder in your project called "patches"
> 3. Inside "patches" folder get the patch from this gist (for convenience) https://gist.github.com/itsam/278a56a1f20a8b80e27c269d9fe83093
>    and name it as react-native-maps+0.27.1.patch
> 4. yarn install or npm install
> 
> Hope that helps

I followed this step by step but I keep getting the warning ! 

- For the first step, I did `yarn add patch-package postinstall-postinstall` (see [The package documentation](https://www.npmjs.com/package/patch-package))
- The second and third step are straightforward ! (I copy/pasted the raw code from the gist)
- The fourth step (I did `yarn install` ) , I only get `success Already up-to-date.`

**What I also tried :** 
- Installing `patch-package` and `postinstall-postinstall` both locally and globally !
- Re-run `npx react-native start` followed by `npx react-native run-android` 

None of the above solved removed the warning ! What should I try ?

**Comment by frankitox** [comment]
Alright, I just wasted a couple of hours with this goddamn warning. I didn't want to patch `react-native-maps` because I'll probably encounter this warning in other libraries, so I wanted a solution that works with all libraries. I first tried using `YellowBox/ignoreWarnings` to no avail (don't know why).

If still interested @FaycalBorsali, I ended up using what this [comment](https://github.com/facebook/metro/issues/287#issuecomment-527075897) suggests, which is an updated answer to this previous [comment](https://github.com/facebook/metro/issues/287#issuecomment-444177106). The solution is really brittle because it matches a regexp on the metro source code, so what regexp you use depends on the metro version you currently have. Other way to go it's just editing the source code yourself, as this [guy](https://github.com/facebook/metro/issues/287#issuecomment-505753690) did. But then you gotta be careful, if you ever update the metro dependency and run `npm install` you'll have to edit the source code again.

**Comment by hathuy98** [comment]
do have someone resolve problem yet ?

**Comment by RG-404** [comment]
I am still having problem with this. Map is not being rendered.

**Comment by diwakarpawar** [comment]
@FaycalBorsali 

Don't forget to add "patch-package" in postinstall in package.json before doing yarn install.
In package.json

"scripts": {
    "postinstall": "patch-package"
}

**Comment by omer-to** [comment]
I just got the same warning, and my app is not opening anymore. Any official solution?

**Comment by sjuanati** [comment]
Even after applying the patch, it doesn't work. No warning now, but when I try to show the map, the app is suddenly closed.
Anyone still supporting this package? after all these months without solution, it doesn't look like something to have in Production.

**Comment by pke** [comment]
@sjuanati the patch works fine. Make sure you have the Google Map SDK ID set in your AppDelegate if you want to use the google map provider. If its not set, the app just crashes.

**Comment by kidfrom** [comment]
I am not sure whether I did something wrong, is the `v0.27.1` broken or am I using it wrong?

This is a component for `Stack.Screen`
```
import React from 'react';
import MapView from 'react-native-maps';

export default function GoSendDestinationDetails() {
  return (
    <MapView
      initialRegion={{
        latitude: 37.78825,
        longitude: -122.4324,
        latitudeDelta: 0.0922,
        longitudeDelta: 0.0421,
      }}
    />
  );
}
```

**Comment by kuasha420** [comment]
I wonder how hard it is to push a new npm package...

**Comment by novonimo** [comment]
until 26 March **2021**  

I've got the same issue with react-native-map and not fixed yet.

no update or new packages, so why this issue closed?

**Comment by tilhi3** [comment]
> 
> 
> until 26 March **2021**
> 
> I've got the same issue with react-native-map and not fixed yet.
> 
> no update or new packages, so why this issue closed?

0.28.0 was released a month ago which should fix this issue. I'm intending to test it the following week.

**Comment by nelsonprsousa** [comment]
Just upgraded from 0.27.1 -> 0.28.0.

I can confirm that this issue is fixed.

Thank you

**Comment by joshjo** [comment]
What is the plan with version 0.28.0? I saw it has commits behind version 0.27.1.

**Comment by MuhammadUmar474** [comment]
I was facing same issue
I forget to enable google map Api from google developer console

**Comment by KrisLau** [comment]
Tested it with 0.28.0 and I'm still getting the error 
![image](https://user-images.githubusercontent.com/46275463/118823683-c4ad1680-b87e-11eb-9232-cc0abbd2b5cb.png)

**Comment by HugoGresse** [comment]
For others, the require cycle has indeed been fixed and released. 
Using `0.29.2` seems to be ok. 
Don't forget to: 
1. update npm dependencies
2. update pod: `cd ios && pod install`
3. re-install the app
4. clear react-native cache: 
    ```
            watchman watch-del-all
        rm -rf $TMPDIR/react-*
        rm -rf $TMPDIR/haste-*
        rm -rf $TMPDIR/metro-*
        npm start -- --reset-cache
    ```
